name: A workflow for my Hello World action
on:   
  workflow_dispatch:
    inputs:
      MY_NAME:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
        
jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Aleks"
